### ISSUE TITLE
Update Course Transfer list views and related list

### ISSUE THREAD

**Issue by robertbwatson** [SFDO-Community-Sprints/transfer-equivalency-credits-eda#22]
- Update "All" list view to show relevant fields
- Update Course Transfers related list on the External Course page layout to show relevant fields

**Comment by robertbwatson** [comment]
Questions to answer before completing this in a scratch org:
* What are the relevant fields we want to show in the All list view?
** Do we want to create any other list views?
* What are the fields we want to show on the Course Transfers related list on the External Course page layout?

**Comment by Kathy-Lueckeman** [comment]
Outdated.
