### ISSUE TITLE
Create and Upload data sets with other Educational Institution Accounts, External Courses, & Course Transfers

### ISSUE THREAD

**Issue by tiagoruivo** [SFDO-Community-Sprints/transfer-equivalency-credits-eda#26]
Create course transfer records for the documented use cases and upload them to the existing data sets to use as example data

**Comment by robertbwatson** [comment]
When updating the existing data set, we should also fix the existing Plan Requirement data so that we don't get errors when uploading the data to an org with the "Validate Program Plan for Nested Plan Requirements" EDA Setting enabled (it's enabled by default for all new orgs)

**Comment by robertbwatson** [comment]
Data can be found here: https://github.com/SFDO-Sprint-2019-Detroit/transfer-equivalency/tree/master/dev_config/data

**Comment by robertbwatson** [comment]
@MatthewBlanski You did some work on this at the sprint, correct? I believe I see we have a data set that includes some external courses, and perhaps fixed the issue with the "Validate Program Plan for Nested Plan Requirements" setting?

**Comment by Kathy-Lueckeman** [comment]
Completed in 2021.
