### ISSUE TITLE
Update Entity Relationship Diagram & Use Cases

### ISSUE THREAD

**Issue by robertbwatson** [SFDO-Community-Sprints/transfer-equivalency-credits-eda#40]
A few new objects were created during the 2020 Virtual Sprint (see #34)

As a result, we need to update the ERD: https://github.com/SFDO-Community-Sprints/transfer-equivalency/wiki/Entity-Relationship-Diagram

We should also consider updating the Use Cases: https://github.com/SFDO-Community-Sprints/transfer-equivalency/wiki/Use-Cases

Note: An ERD was created for this during the 2020 Virtual Sprint - [Starley Flynn](https://github.com/StarleyFlynn) may have it

**Comment by Kathy-Lueckeman** [comment]
Updated in 2021 and again in May 2022 sprint.
