### ISSUE TITLE
Fix test data task (test_data_dev_org)

### ISSUE THREAD

**Issue by robertbwatson** [SFDO-Community-Sprints/transfer-equivalency-credits-eda#42]
When running the `test_data_dev_org` task on the latest feature development in PR #34, I uncovered two issues:

1) The most urgent issue is that the task did not seem to work for me. The test data was not inserted as expected. I received the following error: "Error: 'courses_sf_ids'"

2) I also received a warning: "record_type is deprecated. Just supply a RecordTypeId column declaration and it will be inferred"

**Comment by Kathy-Lueckeman** [comment]
Fixed in 2021
